server:
  port: 8087
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8086/oauth/token
      user-authorization-uri: http://localhost:8086/oauth/authorize
    resource:
      token-info-uri: http://localhost:8086/oauth/check_token
    token:
      store:
        # 配置token存储方式 支持 inMemory、jdbc、redis、jwt，默认inMemory  仅仅配置为jwt时生效，非JwtToken存储方式配置为非jwt即可
        type: jwt
