server:
  port: 8087
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8086/oauth/token
      user-authorization-uri: http://localhost:8086/oauth/authorize
    resource:
      token-info-uri: http://localhost:8086/oauth/check_token