server:
  port: 8088
  #多客户端不配置Cookie的话会导致cookie的name相同，会出现Cookie冲突，冲突会导致登录验证不通过
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSION-ORDER
        path: /
security:
  oauth2:
    token:
      store:
        # 配置token存储方式 支持 inMemory、jdbc、redis、jwt，默认inMemory
        type: jwt
    client:
      client-id: order
      client-secret: secret
      access-token-uri: http://localhost:8086/oauth/token
      user-authorization-uri: http://localhost:8086/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8086/oauth/token_key
      token-info-uri: http://localhost:8086/oauth/check_token
spring:
  application:
    name: sso-client-order
  main:
    allow-bean-definition-overriding: true

