server:
  port: 8088
  #多客户端不配置Cookie的话会导致cookie的name相同，会出现Cookie冲突，冲突会导致登录验证不通过
  servlet:
    session:
      cookie:
        name: ${spring.application.name}-session
spring:
  application:
    name: sso-client-order
  main:
    allow-bean-definition-overriding: true
security:
  oauth2:
    url: http://localhost:8086
    token:
      store:
        # 配置token存储方式 支持 inMemory、jdbc、redis、jwt，默认inMemory
        type: jwt
    client:
      client-id: ${spring.application.name}
      client-secret: secret
      access-token-uri: ${security.oauth2.url}/oauth/token
      user-authorization-uri: ${security.oauth2.url}/oauth/authorize
    resource:
      jwt:
        key-uri: ${security.oauth2.url}/oauth/token_key
      token-info-uri: ${security.oauth2.url}/oauth/check_token


